LICHEE_CHIP:=sun8iw20p1
LICHEE_ARCH:=arm
LICHEE_BRANDY_VER:=2.0
LICHEE_FLASH:=nor
LICHEE_BRANDY_DEFCONF:=sun8iw20p1_defconfig
LICHEE_KERN_VER:=5.4
LICHEE_KERN_DEFCONF:=sun8iw20p1smp_min_defconfig
LICHEE_ROOTFS:=target-arm-linaro-5.3.tar.bz2
LICHEE_REDUNDANT_ENV_SIZE:=0x20000
LICHEE_COMPRESS:=gzip

